l = input().split(' ')
a = float(l[0])
b = float(l[1])
c = float(l[2])
tri = 'TRIANGULO: '+'{:.3f}'.format(a * c / 2)
cir = 'CIRCULO: '+'{:.3f}'.format(3.14159 * c**2)
tra = 'TRAPEZIO: '+'{:.3f}'.format((a + b) * c / 2)
qua = 'QUADRADO: '+'{:.3f}'.format(b*b)
ret = 'RETANGULO: '+'{:.3f}'.format(a * b)
print(tri)
print(cir)
print(tra)
print(qua)
print(ret)